apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: develop

resources:
  - ../../base

images:
  - name: app
    newName: brunohsweber/comercialweber-app
    newTag: 1.0.0-beta.6
