apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

namespace: staging

images:
  - name: app
    newName: brunohsweber/comercialweber-app
    newTag: 1.0.0-beta.6
